INSERT INTO `provider_chains` (`chain_name`, `chain_code`, `chain_id`, `provider`, `created_time`, `updated_time`) VALUES
('Ethereum', 'eth', 1, 'openocean', NOW(), NOW()),
('BNB Chain', 'bsc', 56, 'openocean', NOW(), NOW()),
('zkSync Era', 'zksync', 324, 'openocean', NOW(), NOW()),
('Polygon', 'polygon', 137, 'openocean', NOW(), NOW()),
('Base', 'base', 8453, 'openocean', NOW(), NOW()),
('Linea', 'linea', 59144, 'openocean', NOW(), NOW()),
('Fantom', 'fantom', 250, 'openocean', NOW(), NOW()),
('Avalanche C-Chain', 'avax', 43114, 'openocean', NOW(), NOW()),
('Arbitrum One', 'arbitrum', 42161, 'openocean', NOW(), NOW()),
('Optimism', 'optimism', 10, 'openocean', NOW(), NOW()),
('Moonriver', 'moonriver', 1285, 'openocean', NOW(), NOW()),
('Aurora', 'aurora', 1313161554, 'openocean', NOW(), NOW()),
('Cronos', 'cronos', 25, 'openocean', NOW(), NOW()),
('Harmony', 'harmony', 1666600000, 'openocean', NOW(), NOW()),
('Kava', 'kava', 2222, 'openocean', NOW(), NOW()),
('Metis Andromeda', 'metis', 1088, 'openocean', NOW(), NOW()),
('Celo', 'celo', 42220, 'openocean', NOW(), NOW()),
('Telos', 'telos', 40, 'openocean', NOW(), NOW()),
('Polygon zkEVM', 'polygon_zkevm', 1101, 'openocean', NOW(), NOW()),
('Gnosis', 'xdai', 100, 'openocean', NOW(), NOW()),
('opBNB', 'opbnb', 204, 'openocean', NOW(), NOW()),
('Mantle', 'mantle', 5000, 'openocean', NOW(), NOW()),
('Manta', 'manta', 169, 'openocean', NOW(), NOW()),
('Scroll', 'scroll', 534352, 'openocean', NOW(), NOW()),
('Blast', 'blast', 81457, 'openocean', NOW(), NOW()),
('Mode', 'mode', 34443, 'openocean', NOW(), NOW()),
('Rootstock', 'rootstock', 30, 'openocean', NOW(), NOW()),
('Sei', 'sei', 1329, 'openocean', NOW(), NOW());
